#define POSITION_STATUS 0
#define POSITION_LOCAL_IP 2
#define POSITION_LOCAL_PORT 6
#define POSITION_NTP_SERVER 8
#define POSITION_SERVER_IP 12
#define POSITION_SERVER_PORT 16
#define POSITION_TIMEZONE 18
#define POSITION_VOLTAGE 19
#define POSITION_IRMS 20

enum HTTP_METHOD {GET, POST, PUT, DELETE};
enum HTTP_REQUEST_URI {NONE, CALIBRE, CONFIG, STATUS, SWITCH, SCHEDULE};
